# -*- coding: utf-8 -*-
"""file_handler.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zfflHk1tk6qoV_phzylAeGxpJC2tnh7F
"""

!pip install PyPDF2
import PyPDF2

def extract_text_from_pdf(file) -> str:
    reader = PyPDF2.PdfReader(file)
    text = ""
    for page in reader.pages:
        text += page.extract_text() or ""
    return text