# -*- coding: utf-8 -*-
"""matcher.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uGQBmZcUJr3zwSG1BN03q4OJdQy9xeKo
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer

def tfidf_similarity(resume, jd):
    vectorizer = TfidfVectorizer()
    vectors = vectorizer.fit_transform([resume, jd])
    similarity = cosine_similarity(vectors[0], vectors[1])
    return round(float(similarity[0][0]) * 100, 2)

def bert_similarity(resume, jd):
    model = SentenceTransformer('all-MiniLM-L6-v2')
    embeddings = model.encode([resume, jd])
    similarity = cosine_similarity(
        [embeddings[0]],
        [embeddings[1]]
    )
    return round(float(similarity[0][0]) * 100, 2)

def skill_gap(resume, jd):
    resume_words = set(resume.split())
    jd_words = set(jd.split())

    missing_skills = jd_words - resume_words
    return list(missing_skills)[:20]