# -*- coding: utf-8 -*-
"""preprocess.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7Io9fLyCw5vJ45rgUNTS8GnB6aZd5Rw
"""

import spacy
import nltk
import re
from nltk.corpus import stopwords

nltk.download('stopwords')
nlp = spacy.load("en_core_web_sm")
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = re.sub(r'\W', ' ', text)
    text = text.lower()
    doc = nlp(text)
    tokens = [
        token.lemma_ for token in doc
        if token.text not in stop_words and token.is_alpha
    ]
    return " ".join(tokens)