# -*- coding: utf-8 -*-
"""similarity.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1di6FdlQJjANie-PRe06MzML-nTpkCo3f
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
import numpy as np

# Load model once (important for performance)
bert_model = SentenceTransformer("all-MiniLM-L6-v2")

def compute_tfidf_similarity(text1: str, text2: str) -> float:
    vectorizer = TfidfVectorizer()
    vectors = vectorizer.fit_transform([text1, text2])
    score = cosine_similarity(vectors[0], vectors[1])[0][0]
    return round(score * 100, 2)

def compute_bert_similarity(text1: str, text2: str) -> float:
    embeddings = bert_model.encode([text1, text2])
    score = cosine_similarity(
        [embeddings[0]],
        [embeddings[1]]
    )[0][0]
    return round(score * 100, 2)