# -*- coding: utf-8 -*-
"""skill_extractor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I5TtL_oN2RjvFJC6faFomMm4yJo_jGRj
"""

def extract_missing_skills(resume_text: str, jd_text: str, top_n: int = 15):
    resume_words = set(resume_text.split())
    jd_words = set(jd_text.split())

    missing = jd_words - resume_words

    return list(missing)[:top_n]